export const firebaseConfig = {
	apiKey: 'AIzaSyCzenI1WpO2JBbltc3ARFKTCJyUumY-zkk',
	authDomain: 'rbtrack-ab0e9.firebaseapp.com',
	databaseURL: 'https://rbtrack-ab0e9.firebaseio.com',
	projectId: 'rbtrack-ab0e9',
	storageBucket: 'rbtrack-ab0e9.appspot.com',
	messagingSenderId: '381452575978',
	appId: '1:381452575978:web:9999b9c4b6d38967',
};

export const actionsOptions = [
	{ label: '', value: null },
	{ label: 'Stay', value: 'stay' },
	{ label: 'Walk', value: 'walk' },
	{ label: 'Car', value: 'car' },
	{ label: 'Bike', value: 'bike' },
	{ label: 'e-Bike', value: 'e-bike' },
	{ label: 'Scooter', value: 'scooter' },
	{ label: 'e-Scooter', value: 'e-scooter' },
	{ label: 'e-Board', value: 'rb' },
	{ label: 'e-Board Bad Road', value: 'rb-bad' },
];

export const csvHeader = [
	{ label: 'id', key: 'id' },
	{ label: 'x1', key: 'x1' },
	{ label: 'x2', key: 'x2' },
	{ label: 'x3', key: 'x3' },
	{ label: 'x4', key: 'x4' },
	{ label: 'x5', key: 'x5' },
	{ label: 'x6', key: 'x6' },
	{ label: 'x7', key: 'x7' },
	{ label: 'x8', key: 'x8' },
	{ label: 'x9', key: 'x9' },
	{ label: 'x10', key: 'x10' },
	{ label: 'x11', key: 'x11' },
	{ label: 'x12', key: 'x12' },
	{ label: 'x13', key: 'x13' },
	{ label: 'x14', key: 'x14' },
	{ label: 'x15', key: 'x15' },
	{ label: 'y1', key: 'y1' },
	{ label: 'y2', key: 'y2' },
	{ label: 'y3', key: 'y3' },
	{ label: 'y4', key: 'y4' },
	{ label: 'y5', key: 'y5' },
	{ label: 'y6', key: 'y6' },
	{ label: 'y7', key: 'y7' },
	{ label: 'y8', key: 'y8' },
	{ label: 'y9', key: 'y9' },
	{ label: 'y10', key: 'y10' },
	{ label: 'y11', key: 'y11' },
	{ label: 'y12', key: 'y12' },
	{ label: 'y13', key: 'y13' },
	{ label: 'y14', key: 'y14' },
	{ label: 'y15', key: 'y15' },
	{ label: 'z1', key: 'z1' },
	{ label: 'z2', key: 'z2' },
	{ label: 'z3', key: 'z3' },
	{ label: 'z4', key: 'z4' },
	{ label: 'z5', key: 'z5' },
	{ label: 'z6', key: 'z6' },
	{ label: 'z7', key: 'z7' },
	{ label: 'z8', key: 'z8' },
	{ label: 'z9', key: 'z9' },
	{ label: 'z10', key: 'z10' },
	{ label: 'z11', key: 'z11' },
	{ label: 'z12', key: 'z12' },
	{ label: 'z13', key: 'z13' },
	{ label: 'z14', key: 'z14' },
	{ label: 'z15', key: 'z15' },
	{ label: 'label', key: 'label' },
];
